drop table Purchase;
drop table Order_shop;
drop table Product_Supplier;
drop table Request;
drop table Product;
drop table Type_Product;
drop table Point_of_Sale;
drop table Type_Point_of_Sale;
drop table Invoice;
drop table Employee;
drop table Post;
drop table Supplier;
drop table Buyer;
drop table Users;

create table Users (
                                    ID_Users NUMBER (20,0) generated by default on null as identity primary key,
                                    Login varchar2(50) not null unique,
                                    Password varchar2(50) not null,
                                    Role varchar2(50) not null
);

insert into Users values (NULL, 'admin', 'admin', 'administrator');
insert into Users values (NULL, '1', '12345', 'seller');
insert into Users values (NULL, '2', '54321', 'manager');
insert into Users values (NULL, '3', '1234', 'seller');

create table Type_Point_of_Sale (
                                    ID_Type_Point_of_Sale NUMBER (20,0) generated by default on null as identity primary key,
                                    Name_Type_Point_of_Sale varchar2(50) not null unique
);

insert into Type_Point_of_Sale values (NULL,'Shop');
insert into Type_Point_of_Sale values (NULL,'Department Store');

create table Point_of_Sale (
                               ID_Point_of_Sale NUMBER (20,0) generated by default on null as identity primary key,
                               ID_Type_Point_of_Sale NUMBER (20,0) not null,
                               Name_Point_of_Sale varchar2(50) not null unique,
                               Number_Sections number(12,0) not null,
                               Number_Halls number(12,0) not null,
                               Number_Stalls number(12,0) not null,
                               "SIZE(m^2)" number(12,4) not null,
                               "Rental_Price($)" number(12,4) not null,
                               "Utilities($)" number(12,4) not null,
                               FOREIGN KEY (ID_Type_Point_of_Sale)  REFERENCES Type_Point_of_Sale (ID_Type_Point_of_Sale),
                               CHECK (Number_Sections >= 0),
                               CHECK (Number_Halls >= 0),
                               CHECK (Number_Stalls > 0),
                               CHECK ("SIZE(m^2)" > 0),
                               CHECK ("Rental_Price($)" > 0),
                               CHECK ("Rental_Price($)" > 0)
);

insert into Point_of_Sale values (NULL, 2, 'auchan1', 1, 1, 4, 1000, 5000, 400);
insert into Point_of_Sale values (NULL, 1, 'auchan2', 1, 2, 2, 500, 3000, 250);


create table Post (
                            ID_Post NUMBER (20,0) generated by default on null as identity primary key,
                            Name_Post varchar2(50) not null unique
);

insert into Post values (NULL, 'Seller');
insert into Post values (NULL, 'Manager');

create table Employee (
                          ID_Employee NUMBER (20,0) generated by default on null as identity primary key,
                          ID_Post NUMBER (20,0) not null,
                          ID_Point_Of_Sale NUMBER (20,0) not null,
                          Salary number(12,4) not null,
                          First_Name varchar2(50) not null,
                          Last_Name varchar2(50) not null,
                          Number_Phone varchar2(20) not null,
                          FOREIGN KEY (ID_Post)  REFERENCES Post (ID_Post),
                          CHECK (Salary > 0)
);

insert into Employee values (NULL, 1, 1,  500, 'Ivan', 'Ivanov', '89537649060');
insert into Employee values (NULL, 2, 1,  1000, 'Ivan', 'Sergeev', '89537749060');
insert into Employee values (NULL, 1, 1,  600, 'Alina', 'Kuznetsova', '89535667667');

create table Invoice (
                         ID_Invoice NUMBER (20,0) generated by default on null as identity primary key,
                         ID_Employee NUMBER (20,0) not null,
                         "Date" DATE not null,
                         Number_of_Pieces number(12,0),
                         "Quantity(weight_in_grams)" number(12,4),
                         FOREIGN KEY (ID_Employee)  REFERENCES Employee (ID_Employee),
                         CHECK (Number_of_Pieces >= 0),
                         CHECK ( "Quantity(weight_in_grams)" >= 0)
);

insert into Invoice values (NULL,1,to_date('20220325','YYYYMMDD'), 1, 0);
insert into Invoice values (NULL,1,to_date('20200325','YYYYMMDD'), 1, 0);

create table Supplier (
                         ID_Supplier NUMBER (20,0) generated by default on null as identity primary key,
                         Name_Supplier varchar2(50) not null unique,
                         Active number (1,0) not null
);

insert into Supplier values (NULL,'Ozon', 1);
insert into Supplier values (NULL,'SibirPromTorg', 1);

create table Buyer (
                       ID_Buyer NUMBER (20,0) generated by default on null as identity primary key,
                       First_Name varchar2(50) not null,
                       Last_Name varchar2(50) not null,
                       "Money_Spent($)" number(12,4),
                       Number_Card  NUMBER (20,0) generated always as (ID_Buyer+100000) virtual,
                       CHECK ("Money_Spent($)" >= 0)
);

insert into Buyer (ID_Buyer,First_Name,Last_Name,"Money_Spent($)") values (NULL, 'unknown buyer', '-', 0);
insert into Buyer (ID_Buyer,First_Name,Last_Name,"Money_Spent($)") values (NULL, 'Arkadiy', 'Ponomarev', 2);
insert into Buyer (ID_Buyer,First_Name,Last_Name,"Money_Spent($)") values (NULL,'Boris','Nemov', 2);


create table Type_Product (
                       ID_Type_Product NUMBER (20,0) generated by default on null as identity primary key,
                       Name_Type_Product varchar2(50) not null unique
);

insert into Type_Product values (NULL,'Snacks');
insert into Type_Product values (NULL,'Cosmetics');

create table Product (
                         ID_Product NUMBER (20,0) generated by default on null as identity primary key,
                         ID_Type_Product NUMBER (20,0) not null,
                         ID_Point_of_Sale NUMBER (20,0) not null,
                         Name_Product varchar2(50) not null,
                         Article_Number varchar2(50) not null unique,
                         Number_of_Pieces number(12,0),
                         "Quantity(weight_in_grams)" number(12,4),
                         "Сost per piece" number(12,4),
                         "Cost per 100g" number(12,4),
                         FOREIGN KEY (ID_Type_Product)  REFERENCES Type_Product (ID_Type_Product),
                         FOREIGN KEY (ID_Point_of_Sale)  REFERENCES Point_of_Sale (ID_Point_of_Sale),
                         CHECK (Number_of_Pieces >= 0),
                         CHECK ("Quantity(weight_in_grams)" >= 0),
                         CHECK ("Сost per piece" >= 0),
                         CHECK ("Cost per 100g" >= 0)
);

insert into Product values (NULL, 1, 1, 'Lays', '100000', 1, 0, 2, 0);
insert into Product values (NULL, 2, 2, 'Liquid Lipstick Beauty Killer', '100001',1 ,0, 10, 0);
insert into Product values (Null, 2, 2, 'L''OREAL PARIS VOLUME MILLION LASHES MASCARA', '100002', 4, 0,15,0);

create table Purchase (
                          ID_Purchase NUMBER (20,0) generated by default on null as identity primary key,
                          ID_Point_of_Sale NUMBER (20,0) not null,
                          ID_Product NUMBER (20,0)  not null,
                          ID_Invoice NUMBER (20,0) not null,
                          ID_Buyer NUMBER (20,0) not null,
                          "Cost($)" number(12,4) not null,
                          FOREIGN KEY (ID_Point_of_Sale)  REFERENCES Point_of_Sale (ID_Point_of_Sale),
                          FOREIGN KEY (ID_Product)  REFERENCES Product (ID_Product),
                          FOREIGN KEY (ID_Invoice)  REFERENCES Invoice (ID_Invoice),
                          FOREIGN KEY (ID_Buyer)  REFERENCES Buyer (ID_Buyer),
                          CHECK ("Cost($)" >= 0)
);

insert into Purchase values (NULL, 1, 1, 1, 2, 2);
insert into Purchase values (NULL, 1, 1, 2, 3, 2);

create table Request (
                         ID_Request NUMBER (20,0) generated by default on null as identity primary key,
                         ID_Point_of_Sale NUMBER (20,0) not null,
                         ID_Product NUMBER (20,0)  not null,
                         Number_of_Pieces number(12,0),
                         "Quantity(weight_in_grams)" number(12,4),
                         Status varchar2(12) not null,
                         FOREIGN KEY (ID_Point_of_Sale)  REFERENCES Point_of_Sale (ID_Point_of_Sale),
                         FOREIGN KEY (ID_Product)  REFERENCES Product (ID_Product),
                         CHECK (Number_of_Pieces >= 0),
                         CHECK ("Quantity(weight_in_grams)" >=0)
);

create table Product_Supplier (
                                  ID_Product_Supplier NUMBER (20,0) generated by default on null as identity primary key,
                                  ID_Type_Product NUMBER (20,0) not null,
                                  ID_Supplier NUMBER (20,0) not null,
                                  Name_Product varchar2(50) not null unique,
                                  Number_of_Pieces number(12,0),
                                  "Quantity(weight_in_grams)" number(12,4),
                                  "Сost per piece" number(12,4),
                                  "Cost per 100g" number(12,4),
                                  FOREIGN KEY (ID_Type_Product)  REFERENCES Type_Product (ID_Type_Product),
                                  FOREIGN KEY (ID_Supplier)  REFERENCES Supplier (ID_Supplier),
                                  CHECK (Number_of_Pieces >= 0),
                                  CHECK ("Quantity(weight_in_grams)" >= 0),
                                  CHECK ("Сost per piece" >= 0),
                                  CHECK ("Cost per 100g" >= 0)
);

insert into Product_Supplier values (Null, 1, 1, 'Lays', 100, 0, 1.5, 0);

create table Order_shop (
                            ID_Order_shop NUMBER (20,0) generated by default on null as identity primary key,
                            ID_Point_of_Sale NUMBER (20,0) not null,
                            ID_Product_Supplier NUMBER (20,0)  not null,
                            ID_Invoice NUMBER (20,0) not null,
                            ID_Supplier NUMBER (20,0) not null,
                            "Cost($)" number(12,4) not null,
                            Status varchar2(12) not null,
                            Number_Order_Shop  NUMBER (20,0) generated always as (ID_Order_shop+100000) virtual,
                            FOREIGN KEY (ID_Point_of_Sale)  REFERENCES Point_of_Sale (ID_Point_of_Sale),
                            FOREIGN KEY (ID_Product_Supplier)  REFERENCES Product_Supplier (ID_Product_Supplier),
                            FOREIGN KEY (ID_Invoice)  REFERENCES Invoice (ID_Invoice),
                            FOREIGN KEY (ID_Supplier)  REFERENCES Supplier (ID_Supplier),
                            CHECK ("Cost($)" >= 0)
);
