drop table Purchase;
drop table Order_shop;
drop table Point_of_Sale;
drop table Type_Point_of_Sale;
drop table Product;
drop table Type_Product;
drop table Invoice;
drop table Employee;
drop table Post;
drop table Supplier;
drop table Buyer;

create table Type_Point_of_Sale (
                                    ID_Type_Point_of_Sale NUMBER (20,0) generated by default on null as identity primary key,
                                    Name_Type_Point_of_Sale varchar2(50) not null
);

insert into Type_Point_of_Sale values (NULL,'Shop');
insert into Type_Point_of_Sale values (NULL,'Department Store');

create table Point_of_Sale (
                               ID_Point_of_Sale NUMBER (20,0) generated by default on null as identity primary key,
                               ID_Type_Point_of_Sale NUMBER (20,0) not null,
                               Number_Sections number(12,0) not null,
                               Number_Halls number(12,0) not null,
                               Number_Stalls number(12,0) not null,
                               "SIZE(m^2)" number(12,4) not null,
                               "Rental_Price($)" number(12,4) not null,
                               "Utilities($)" number(12,4) not null,
                               FOREIGN KEY (ID_Type_Point_of_Sale)  REFERENCES Type_Point_of_Sale (ID_Type_Point_of_Sale)
);

insert into Point_of_Sale values (NULL, 2, 1, 1, 4, 1000, 5000, 400);
insert into Point_of_Sale values (NULL, 1, 0, 1, 2, 500, 3000, 250);


create table Post (
                            ID_Post NUMBER (20,0) generated by default on null as identity primary key,
                            Name_Post varchar2(50) not null
);

insert into Post values (NULL, 'Seller');
insert into Post values (NULL, 'Manager');

create table Employee (
                          ID_Employee NUMBER (20,0) generated by default on null as identity primary key,
                          ID_Post NUMBER (20,0) not null,
                          Salary number(12,4) not null,
                          First_Name varchar2(50) not null,
                          Last_Name varchar2(50) not null,
                          Number_Phone varchar2(20) not null,
                          FOREIGN KEY (ID_Post)  REFERENCES Post (ID_Post)
);

insert into Employee values (NULL, 1, 500, 'Ivan', 'Ivanov', '89537649060');
insert into Employee values (NULL, 2, 1000, 'Ivan', 'Sergeev', '89537749060');
insert into Employee values (NULL, 1, 600, 'Alina', 'Kuznetsova', '89535667667');

create table Invoice (
                         ID_Invoice NUMBER (20,0) generated by default on null as identity primary key,
                         ID_Employee NUMBER (20,0) not null,
                         "Date" DATE not null,
                         FOREIGN KEY (ID_Employee)  REFERENCES Employee (ID_Employee)
);

insert into Invoice values (NULL,1,to_date('20220325','YYYYMMDD'));
insert into Invoice values (NULL,1,to_date('20220325','YYYYMMDD'));

create table Supplier (
                         ID_Supplier NUMBER (20,0) generated by default on null as identity primary key,
                         Name_Supplier varchar2(50) not null
);

insert into Supplier values (NULL,'Ozon');
insert into Supplier values (NULL,'SibirPromTorg');

create table Buyer (
                       ID_Buyer NUMBER (20,0) generated by default on null as identity primary key,
                       First_Name varchar2(50) not null,
                       Last_Name varchar2(50) not null,
                       "Money_Spent($)" number(12,4)
);

insert into Buyer values (NULL,'Arkadiy', 'Ponomarev', 40);
insert into Buyer values (NULL,'Boris','Nemov', 70);

create table Type_Product (
                       ID_Type_Product NUMBER (20,0) generated by default on null as identity primary key,
                       Name_Type_Product varchar2(50) not null
);

insert into Type_Product values (NULL,'Potato');
insert into Type_Product values (NULL,'Lipstick');

create table Product (
                         ID_Product NUMBER (20,0) generated by default on null as identity primary key,
                         ID_Type_Product NUMBER (20,0) not null,
                         Article_Number varchar2(50) not null,
                         Number_of_Pieces number(12,0),
                         "Quantity(weight_in_grams)" number(12,4),
                         FOREIGN KEY (ID_Type_Product)  REFERENCES Type_Product (ID_Type_Product)
);

insert into Product values (NULL,1,100000,0,10000);
insert into Product values (NULL,2,100001,1,0);

create table Purchase (
                          ID_Purchase NUMBER (20,0) generated by default on null as identity primary key,
                          ID_Point_of_Sale NUMBER (20,0) not null,
                          ID_Product NUMBER (20,0)  not null,
                          ID_Invoice NUMBER (20,0) not null,
                          ID_Buyer NUMBER (20,0) not null,
                          "Cost($)" number(12,4) not null,
                          FOREIGN KEY (ID_Point_of_Sale)  REFERENCES Point_of_Sale (ID_Point_of_Sale),
                          FOREIGN KEY (ID_Product)  REFERENCES Product (ID_Product),
                          FOREIGN KEY (ID_Invoice)  REFERENCES Invoice (ID_Invoice),
                          FOREIGN KEY (ID_Buyer)  REFERENCES Buyer (ID_Buyer)
);

insert into Purchase values (NULL, 1, 1, 1, 1, 40);
insert into Purchase values (NULL, 2, 2, 2, 2, 70);

create table Order_shop (
                            ID_Composition_of_Invoice NUMBER (20,0) generated by default on null as identity primary key,
                            ID_Point_of_Sale NUMBER (20,0) not null,
                            ID_Product NUMBER (20,0)  not null,
                            ID_Invoice NUMBER (20,0) not null,
                            ID_Supplier NUMBER (20,0) not null,
                            "Cost($)" number(12,4) not null,
                            FOREIGN KEY (ID_Point_of_Sale)  REFERENCES Point_of_Sale (ID_Point_of_Sale),
                            FOREIGN KEY (ID_Product)  REFERENCES Product (ID_Product),
                            FOREIGN KEY (ID_Invoice)  REFERENCES Invoice (ID_Invoice),
                            FOREIGN KEY (ID_Supplier)  REFERENCES Supplier (ID_Supplier)
);